export class PlayerImages {
  images: { [key: string]: string };
  constructor() {
    this.images = {
      run0: "image/player/run/0.png",
      run1: "image/player/run/1.png",
      run2: "image/player/run/2.png",
      run3: "image/player/run/3.png",
      run4: "image/player/run/4.png",
      run5: "image/player/run/5.png",
      idle0: "image/player/idle-sword/0.png",
      idle1: "image/player/idle-sword/1.png",
      idle2: "image/player/idle-sword/2.png",
      idle3: "image/player/idle-sword/3.png",
      idle4: "image/player/idle-sword/4.png",
      idle5: "image/player/idle-sword/5.png",
      attack1_0: "image/player/attack/1-0.png",
      attack1_1: "image/player/attack/1-1.png",
      attack1_2: "image/player/attack/1-2.png",
      attack1_3: "image/player/attack/1-3.png",
      attack1_4: "image/player/attack/1-4.png",
      attack1_5: "image/player/attack/1-5.png",
      attack2_0: "image/player/attack/2-0.png",
      attack2_1: "image/player/attack/2-1.png",
      attack2_2: "image/player/attack/2-2.png",
      attack2_3: "image/player/attack/2-3.png",
      attack2_4: "image/player/attack/2-4.png",
      attack2_5: "image/player/attack/2-5.png",
      attack3_0: "image/player/attack/3-0.png",
      attack3_1: "image/player/attack/3-1.png",
      attack3_2: "image/player/attack/3-2.png",
      attack3_3: "image/player/attack/3-3.png",
      // attack3_4: 'image/attack/3-4.png',
      // attack3_5: 'image/attack/3-5.png',
      jump0: "image/player/jump/0.png",
      jump1: "image/player/jump/1.png",
      jump2: "image/player/jump/2.png",
      jump3: "image/player/jump/3.png",
    };
  }
}
